### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by OrigWhiteKenyan** [toaarnio/imgio#1]
Hi, I'm new to Python and scripts and such. I installed imgio through _pip_ but I don't really know how to access and use imgio. I'm wanting to create text images for use with an RGB Matrix on a Raspberry Pi and this would help streamline this immensely if I'm able to do that with this program. Thanks for any help you can give me

**Comment by toaarnio** [comment]
Hi, thanks for your interest and sorry for the delay!

Here's a simple piece of code that converts a PNG into a PPM.
```
import imgio

image, maxval = imgio.imread("foo.png")
imgio.imwrite("foo.ppm", image, maxval)
```

I'm not sure if the libraries that imgio depends on are available on Raspberry (namely, numpy, piexif and imread), but if they are, then I'm not expecting any problems. This library itself is written in very basic Python.

**Comment by OrigWhiteKenyan** [comment]
Okay so you have to import Imgio into a python script, if I’m understanding that correctly. Also, I am wanting to create a PNM image from scratch, vs converting a pre-made png image into one. Is that something that imgio can do or is that not possible?

**Comment by toaarnio** [comment]
That's correct, you import imgio the same way you import sys, os, time and all the other Python packages that you need for your script.

To create a PNM image from scratch, you need to write your pixels into a NumPy array and then pass that array to imwrite: `imgio.imwrite("myimage.pnm", my_array)`.

As for how to generate an image with text in it, you probably need to look up a font rendering package, but I have no experience with those so can't help you there.
